travel/article/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = 'article'

urlpatterns = [

	# Method 2
	url(r'^$', views.ArticleIndexView.as_view(), name = 'articleindex'),

	# Method 2
	url(r'^(?P<pk>[0-9]+)', views.DetailView.as_view(), name = 'detail'),

	# api links for album /albumapi/
    url(r'^articleapi/', views.ArticleList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

travel/forum/urls.py
from django.conf.urls import url
from . import views

app_name = 'forum'

urlpatterns = [

	# Method 2
	url(r'^$', views.ForumIndexView.as_view(), name = 'forumindex'),

	# Method 2
	url(r'^(?P<slug>[-\w]+)/$', views.DetailForumView.as_view(), name = 'detail'),


	url(r'^(?P<slug>[-\w]+)/comment/$', views.add_comment, name='add_comment'),


]

travel/travel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    # Admin site url
    url(r'^admin/', admin.site.urls),

    # Article site url - Default
    url(r'^', include('article.urls')),

    # Add Article site url
    url(r'^addarticle/', include('addarticle.urls')),

    url(r'^addforum/', include('addforum.urls')),

    # Forum site url
    url(r'^forum/', include('forum.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
 #   urlpatterns = static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
  #  urlpatterns = static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

travel/article/models.py
from django.db import models

# Create your models here.
class Tags(models.Model):
	label = models.CharField(max_length = 30)

	def __str__(self):
		return self.label

class Article(models.Model):
    article_title = models.CharField(max_length = 250)
    description = models.TextField()
    content = models.TextField()
    author = models.CharField(max_length = 250)
    date_published = models.DateTimeField(auto_now=True)
    # thumbnail = models.ImageField(upload_to = 'media/' , default = 'media/travel1.jpg')
    # header = models.ImageField(upload_to = 'media/', default = 'media/travel1.jpg')

    def __str__(self):
        return self.article_title + ' - ' + self.description

travel/article/views.py
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import ArticleSerializer
from django.views import generic

from .models import Article

class ArticleIndexView(generic.ListView):
	template_name = 'article/articleindex.html'
	context_object_name = 'all_article'

	def get_queryset(self):
		return Article.objects.all()

class DetailView(generic.DetailView):
	model = Article
	template_name = 'article/detail.html'

class ArticleList(APIView):

	def get(self, request):
		articles = Article.objects.all()
		serializer = ArticleSerializer(articles, many = True)
		return Response(serializer.data)

	def post(self, request):
		serializer = ArticleSerializer(data=request.data)
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data, status=status.HTTP_201_CREATED)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ArticleDetail(APIView):
	
	def get_object(self, pk):
		try:
			return Article.objects.get(pk=pk)
		except Article.DoesNotExist:
			raise Http404

	def get(self, request, pk, format=None):
		articles = self.get_object(pk)
		serializer = ArticleSerializer(articles)
		return Response(serializer.data)

	def put(self, request, pk, format=None):
		articles = self.get_object(pk)
		serializer = ArticleSerializer(articles, data=request.data)
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

	def delete(self, request, pk, format=None):
		articles = self.get_object(pk)
		articles.delete()
		return Response(status=status.HTTP_204_NO_CONTENT)

travel/article/templates/article/articleindex.html
{% extends 'articlebase.html' %}

{% block title %}
Travelevart
{% endblock %}

{% block content %}
{% load staticfiles%}

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <!-- <div class="jumbotron">
		<div class="container"> -->

			    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide carousel-fade" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
			<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
			<li data-target="#myCarousel" data-slide-to="1"></li>
			<li data-target="#myCarousel" data-slide-to="2"></li>
		</ol>
		<div class="carousel-inner" role="listbox">
			<div class="item active">
				<img class="first-slide" src="{% static 'images/one.jpg' %}" alt="First slide">
					<div class="container">
						<div class="carousel-caption">
							<h1>Welcome to Travelevart</h1>
							<h3>Your one and only travel hub</h3>
							<p><a class="btn btn-lg btn-primary" href="/addarticle/register" role="button">Sign up</a></p>
						</div>
					</div>
			</div>
			<div class="item">
				<img class="second-slide" src="{% static 'images/two.jpg' %}" alt="Second slide">
				<div class="container">
					<div class="carousel-caption">
						<h1>Need idea?</h1>
						<p>Planning for your next travel? Let us help you</p>
						<p><a class="btn btn-lg btn-primary" href="#article-section" role="button">Learn more</a></p>
					</div>
				</div>
			</div>
			<div class="item">
				<img class="third-slide" src="{% static 'images/three.jpg' %}" alt="Third slide">
				<div class="container">
					<div class="carousel-caption">
						<h1>Need partner?</h1>
						<p>Looking for travel partner? Let us help you</p>
						<p><a class="btn btn-lg btn-primary" href="{% url 'forum:forumindex' %}" role="button">Learn more</a></p>
					</div>
				</div>
			</div>
		</div>
		<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div><!-- /.carousel -->

	<div class="container marketing">
		<div id="article-section" class="row">
		{% for article in all_article %}
			<!-- Three columns of text below the carousel -->
			<div class="col-lg-4">
				<h2>{{ article.article_title }}</h2>
				<p>{{ article.description }}</p>
				<p><a class="btn btn-default" href="{% url 'article:detail' article.id %}" role="button">Read More &raquo;</a></p>
			</div><!-- /.col-lg-4 -->
		{% endfor %}
		</div><!-- /.row -->
	</div>>
			
			
				  <!-- START THE FEATURETTES -->

				<!-- {% for article in all_article %} -->

				<!-- {% if article.id|divisibleby:"2" %}				   -->

				<!-- <hr class="featurette-divider">
				
					  <div class="row featurette">
						<div class="col-md-7 col-md-push-5">
								<h2 class="featurette-heading">{{ article.article_title }}</h2>
								<p class="lead">{{ article.description }}</p>
								<p><a class="btn btn-default" href="{% url 'article:detail' article.id %}" role="button">Read More &raquo;</a></p>  
						</div> -->
						<!-- <div class="col-md-5 col-md-pull-7">
								<img class="featurette-image img-responsive center-block" data-src="{{ article.thumbnail.url }}" alt="Generic placeholder image">
						</div> -->
					  <!-- </div> -->

						<!-- {% else %}

						<hr class="featurette-divider">
						
							  <div class="row featurette">
									<div class="col-md-7"> -->
									  <!-- <h2 class="featurette-heading">{{ article.article_title }} First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
									  <p class="lead">{{ article.description }} Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
									  <p><a class="btn btn-default" href="{% url 'article:detail' article.id %}" role="button">Read More &raquo;</a></p>   -->
								  <!-- </div>
							  <div class="col-md-5">
								  <img class="featurette-image img-responsive center-block" data-src="{{ article.thumbnail.url }}" alt="Generic placeholder image"> 
								</div> -->
							  <!-- </div> -->


						<!-- {% endif %} -->
				  
				<!-- {% endfor %}		 -->

			
				  <!-- <hr class="featurette-divider"> -->
			
				  <!-- /END THE FEATURETTES -->


{% endblock %}

travel/article/templates/article/detail.html
{% extends 'articlebase.html' %}

{% block title %}
Article
{% endblock %}

{% block content %}

<div class="container container-detail">

    <div class="page-header">
        <h1>{{ article.article_title }}</h1>
        <p class="text-muted">Author : {{ article.author }}, Date Published : {{ article.date_published }}</p>
    </div>
    <p class="lead blog-description">{{ article.content }}</p>

    <!-- <div class="blog-header">
        <h1 class="blog-title">{{ article.article_title }}</h1>
        <p class="lead blog-description">{{ article.description }}</p>
        <p class="blog-post-meta">{{ article.author }}</p>
        <p class="blog-post-meta">{{ article.date_published }}</p>
    </div>
    
    <div class="row">    
        <div class="col-sm-8 blog-main">    
            <div class="blog-post">
                <h2 class="blog-post-title">{{ article.article_title }}</h2>
                <p>{{ article.content }}</p>
            </div>
        </div>
    </div> -->
    
{% endblock %}