travel/addarticle/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout


app_name = 'addarticle'

urlpatterns = [
	url(r'^$', views.AddArticleFormView.as_view(), name = 'addarticle'),
	url(r'^register/$', views.UserFormView.as_view(), name = 'register'),
	url(r'^login/$', login, {'template_name': 'addarticle/login.html'}, name = 'login'),
	url(r'^logout/$', logout, name='logout'),
	url(r'^allusers/$', views.MemberView.as_view(), name = 'allusers'),
] 

travel/addforum/urls.py
from django.conf.urls import url
from . import views


app_name = 'addforum'

urlpatterns = [
	url(r'^$', views.AddForumFormView.as_view(), name = 'addforum'),
] 

travel/article/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = 'article'

urlpatterns = [

	# Method 2
	url(r'^$', views.ArticleIndexView.as_view(), name = 'articleindex'),

	# Method 2
	url(r'^(?P<pk>[0-9]+)', views.DetailView.as_view(), name = 'detail'),

	# api links for album /albumapi/
    url(r'^articleapi/', views.ArticleList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

travel/forum/urls.py
from django.conf.urls import url
from . import views

app_name = 'forum'

urlpatterns = [

	# Method 2
	url(r'^$', views.ForumIndexView.as_view(), name = 'forumindex'),

	# Method 2
	url(r'^(?P<slug>[-\w]+)/$', views.DetailForumView.as_view(), name = 'detail'),


	url(r'^(?P<slug>[-\w]+)/comment/$', views.add_comment, name='add_comment'),


]

travel/travel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    # Admin site url
    url(r'^admin/', admin.site.urls),

    # Article site url - Default
    url(r'^', include('article.urls')),

    # Add Article site url
    url(r'^addarticle/', include('addarticle.urls')),

    url(r'^addforum/', include('addforum.urls')),

    # Forum site url
    url(r'^forum/', include('forum.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
 #   urlpatterns = static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
  #  urlpatterns = static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

travel/templates/articlebase.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title%} Travelevart {% endblock %}</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!--Font-->
    <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css?family=Armata" rel="stylesheet">
    <!--Our CSS-->
    <link rel = "stylesheet" type = "text/css" href="{% static 'style.css' %}"> 
    <link rel =" shortcut icon" href = "{% static 'favicon/favicon.ico' %}"/>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
    <script src="{% static 'site.js' %}"></script>
  </head>

  <body>
      <div class="navbar-wrapper">
          <div class="container">
    <!--Navigation Bar-->
    <nav class="navbar navbar-default navbar-static-top" role="navigation"> 
      <div class="container">

        <!-- Header-->
        <div class="navbar-header">

          <!--Collapse Button-->
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-brand-centered">
		        <span class="sr-only">Toggle navigation</span>            
            <span class="icon-bar"></span>  
            <span class="icon-bar"></span>  
            <span class="icon-bar"></span>  
          </button>
          
          <!--Logo links to main page-->
          <a class="navbar-brand navbar-brand-centered" href="{% url 'article:articleindex' %}">Travelevart</a>
        </div>
        

        <!--Other navigation bar items-->
        <div class="collapse navbar-collapse" id="navbar-brand-centered">

          <!--Left side-->
          <ul class="nav navbar-nav">
            <li class="">
              <a href="{% url 'article:articleindex' %}">
                Article
              </a>
            </li>
            <li>
              <a href="{% url 'forum:forumindex' %}">
                Forum
              </a>
            </li>
          </ul>
          
          <!--Logged in-->
          {% if user.is_authenticated %}

          <!--Right side-->

          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="">
                {{ request.user.username }}
              </a>
            </li>
            <li class="">
                <a href="/addarticle/allusers">
                <span class="fa fa-users fa-1x" aria-hidden="true" data-toggle="tooltip" title="Members"></span>
              </a>
            </li>  
            <li class="">
              <a href="{% url 'addarticle:addarticle' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true" data-toggle="tooltip" title="Add New Article"></span>
              </a>
            </li>
            <li class="">
              <a href="/addarticle/logout">
                <span class="fa fa-sign-out fa-1x" aria-hidden="true" data-toggle="tooltip" title="Sign Out"></span>
              </a>
            </li>            
          </ul>

          {% else %}

          <!--Not Logged in-->
          <!--Right side-->
          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="/addarticle/login">
                Login
              </a>
            </li>
            <li class="">
              <a href="/addarticle/register">
                Register
              </a>
            </li>             
          </ul>   

          {% endif %}      

        </div>
      </div>  
    </nav>

  </div>
</div>

    {% block content %}

    {% endblock %}

    <div class="container">

    <hr>

    <footer>
      <p>&copy; {% now "Y" %} WOC 7012 - Web Framework Group Project.</p>
    </footer>

    </div>

    <script src="https://use.fontawesome.com/5067f5ef39.js"></script>

  </body>
</html>

travel/templates/forumbase.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title%} Travelevart {% endblock %}</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!--Font-->
    <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet'>
    <!--Our CSS-->
    <link rel = "stylesheet" type = "text/css" href="{% static 'style.css' %}"> 
    <link rel =" shortcut icon" href = "{% static 'favicon/favicon.ico' %}"/>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
    <script src="{% static 'site.js' %}"></script>
  </head>

  <body>
      <div class="navbar-wrapper">
          <div class="container">
    <!--Navigation Bar-->
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation"> 
      <div class="container">

        <!-- Header-->
        <div class="navbar-header">

          <!--Collapse Button-->
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-brand-centered">
            <span class="sr-only">Toggle navigation</span>            
            <span class="icon-bar"></span>  
            <span class="icon-bar"></span>  
            <span class="icon-bar"></span>  
          </button>
          
          <!--Logo links to main page-->
          <a class="navbar-brand navbar-brand-centered" href="{% url 'article:articleindex' %}">Travelevart</a>
        </div>
        

        <!--Other navigation bar items-->
        <div class="collapse navbar-collapse" id="navbar-brand-centered">

          <!--Left side-->
          <ul class="nav navbar-nav">
            <li class="">
              <a href="{% url 'article:articleindex' %}">
                Article
              </a>
            </li>
            <li>
              <a href="{% url 'forum:forumindex' %}">
                Forum
              </a>
            </li>
          </ul>
          
          <!--Logged in-->
          {% if user.is_authenticated %}

          <!--Right side-->

          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="">
                {{ request.user.username }}
              </a>
            </li>
            <li class="">
                <a href="/addarticle/allusers">
                <span class="fa fa-users fa-1x" aria-hidden="true" data-toggle="tooltip" title="Members"></span>
              </a>
            </li>   
            <li class="">
              <a href="{% url 'addforum:addforum' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true" data-toggle="tooltip" title="Add New Article"></span>
              </a>
            </li>
            <li class="">
              <a href="/addarticle/logout">
                <span class="fa fa-sign-out fa-1x" aria-hidden="true" data-toggle="tooltip" title="Sign Out"></span>
              </a>
            </li>            
          </ul>

          {% else %}

          <!--Not Logged in-->
          <!--Right side-->
          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="/addarticle/login">
                Login
              </a>
            </li>
            <li class="">
              <a href="/addarticle/register">
                Register
              </a>
            </li>             
          </ul>   

          {% endif %}      

        </div>
      </div>  
    </nav>

  </div>
</div>

    {% block content %}

    {% endblock %}

    <div class="container">

    <hr>

    <footer>
      <p>&copy; {% now "Y" %} WOC 7012 - Web Framework Group Project.</p>
    </footer>

    </div>

    <script src="https://use.fontawesome.com/5067f5ef39.js"></script>

  </body>
</html>