travel/addforum/urls.py
from django.conf.urls import url
from . import views


app_name = 'addforum'

urlpatterns = [
	url(r'^$', views.AddForumFormView.as_view(), name = 'addforum'),
] 

travel/article/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = 'article'

urlpatterns = [

	# Method 2
	url(r'^$', views.ArticleIndexView.as_view(), name = 'articleindex'),

	# Method 2
	url(r'^(?P<pk>[0-9]+)', views.DetailView.as_view(), name = 'detail'),

	# api links for album /albumapi/
    url(r'^articleapi/', views.ArticleList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

travel/forum/urls.py
from django.conf.urls import url
from . import views

app_name = 'forum'

urlpatterns = [

	# Method 2
	url(r'^$', views.ForumIndexView.as_view(), name = 'forumindex'),

	# Method 2
	url(r'^(?P<slug>[-\w]+)/$', views.DetailForumView.as_view(), name = 'detail'),


	url(r'^(?P<slug>[-\w]+)/comment/$', views.add_comment, name='add_comment'),


]

travel/travel/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    # Admin site url
    url(r'^admin/', admin.site.urls),

    # Article site url - Default
    url(r'^', include('article.urls')),

    # Add Article site url
    url(r'^addarticle/', include('addarticle.urls')),

    url(r'^addforum/', include('addforum.urls')),

    # Forum site url
    url(r'^forum/', include('forum.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
 #   urlpatterns = static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
  #  urlpatterns = static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

travel/addforum/models.py
from django.db import models

# Create your models here.

travel/forum/models.py
from django.db import models
from django.utils import timezone
#from django.core.urlresolvers import reverse
from django.urls import resolve, reverse
from django.contrib.auth.models import User
from autoslug import AutoSlugField
from django.template.defaultfilters import slugify
import datetime

# Create your models here.
class ListForum(models.Model):
	itemlist = models.CharField(max_length = 1500)
	slug = AutoSlugField(populate_from = 'itemlist',unique=True)


	def get_absolute_url(self):
		return reverse('forum:detail',args=[self.slug])


	def __str__(self):
		return self.itemlist

class Forum(models.Model):
    forum_title = models.CharField(max_length = 250)
    #slug = AutoSlugField(populate_from = 'forum_title',unique=True)
    #content = models.TextField()
    #images = models.ImageField(blank=True)
    forum_items = models.ManyToManyField(ListForum)
    def __str__(self):
        return self.forum_title

class Comment(models.Model):
	post = models.ForeignKey(ListForum,on_delete = models.CASCADE,related_name='comments')
	user = models.CharField(max_length=250)
	email = models.EmailField()
	body = models.TextField(max_length=250)
	created = models.DateTimeField(auto_now_add=True)
	approved = models.BooleanField(default=False)

	def approved(self):
		self.approved = True
		self.save()

	def __str__(self):
		return self.user 
		

travel/addforum/forms.py
from django import forms
from forum.models import Forum

class ForumForm(forms.ModelForm):
	class Meta:
		model = Forum
		fields = ('forum_title','forum_items')

travel/forum/forms.py
from django import forms
from .models import Comment,Forum

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('user', 'email', 'body')

class ForumForm(forms.ModelForm):
	class Meta:
		model = Forum
		fields = ('forum_title','forum_items')

travel/addforum/views.py
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import ForumForm
from forum.models import Forum
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin

class AddForumFormView(LoginRequiredMixin, TemplateView):
	login_url = "login/"
	template_name = 'addforum/addforum.html'

	def get(self, request):
		form = ForumForm()
		forums = Forum.objects.all()
		args = {'form': form, 'forums': forums}
		return render(request, self.template_name, args)

	def post(self, request):
			form = ForumForm(request.POST)
			if form.is_valid():
				forum = form.save(commit = False)
				forum_title = form.cleaned_data['forum_title']
				forum_items = form.cleaned_data['forum_items']
				forum.save()
				form.save_m2m()
				args = {'form': form, 'forum_title': forum_title, 'forum_items': forum_items}
				return HttpResponseRedirect(reverse('forum:forumindex'))

travel/forum/views.py
from django.views import generic
from .models import Forum
from .models import Comment
from .forms import CommentForm,ForumForm
from .models import ListForum
from django.shortcuts import render, get_object_or_404, redirect

class ForumIndexView(generic.ListView):
	template_name = 'forum/forumindex.html'
	context_object_name = 'all_forum'

	def get_queryset(self):
		return Forum.objects.all()


class DetailForumView(generic.DetailView):
	model = ListForum
	template_name = 'forum/detail.html'


#addComment
def add_comment(request, slug):
	post = get_object_or_404(ListForum, slug=slug)
	if request.method == 'POST':
		form = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.post = post
			comment.save()
			return redirect('forum:detail', slug=post.slug)
	else:
		form = CommentForm()
	template = 'forum/add_comment.html'
	context = {'form': form}
	return render(request, template, context)

travel/forum/templates/forum/add_comment.html
{% extends 'forumbase.html' %}

{% block content %}
<div style="margin-top: 100px;margin-left: 120px">
	<h1>Add New Comment</h1>
	<form method='POST'>{% csrf_token %}
	{{ form.as_p }}
	<button type="Submit">Submit</button>
	</form>
</div>
	

{% endblock %}

travel/forum/templates/forum/addforum.html
{% extends 'forumbase.html' %}

{% block content %}
<div style="margin-top:500px">
	<h1 style="margin-top: 300px">Add New Forum</h1>
	<form method='POST'>{% csrf_token %}
	{{ form.as_p }}
	<button type="Submit">Submit</button>
	</form>
</div>
	

{% endblock %}

travel/forum/templates/forum/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <title>{% block title%} Travelevart {% endblock %}</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!--Font-->
    <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet'>
    <!--Our CSS-->
    <link rel = "stylesheet" type = "text/css" href="{% static 'article/style.css' %}"> 

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
  </head>

  <body>

    <!--Navigation Bar-->
    <nav class="navbar navbar-inverse "> 
      <div class="container-fluid">

        <!-- Header-->
        <div class="navbar-header">

          <!--Collapse Button-->
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>  
            <span class="icon-bar"></span>  
            <span class="icon-bar"></span>  
          </button>
          
          <!--Logo links to main page-->
          <a class="navbar-brand" href="{% url 'article:articleindex' %}">Travelevart</a>
        </div>
        

        <!--Other navigation bar items-->
        <div class="collapse navbar-collapse" id="topNavBar">

          
          <!--Logged in-->
          {% if user.is_authenticated %}

          <!--Left side-->
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'article:articleindex' %}">
                <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                Article
              </a>
            </li>
            <li class="active">
              <a href="{% url 'forum:forumindex' %}">
                <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                Forum
              </a>
            </li>
          </ul>

          <!--Right side-->
          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
                {{ request.user.username }}
              </a>
            </li>   
            <li class="">
              <a href="/addarticle/logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                Logout
              </a>
            </li>            
          </ul>

          {% else %}

          <!--Not Logged in-->

          <!--Left side-->
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'article:articleindex' %}">
                <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                Article
              </a>
            </li>
            <li class="active">
              <a href="{% url 'forum:forumindex' %}">
                <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                Forum
              </a>
            </li>
          </ul>

          <!--Right side-->
          <ul class="nav navbar-nav navbar-right">
            <li class="">
              <a href="/addarticle/login">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                Login
              </a>
            </li>
            <li class="">
              <a href="/addarticle/register">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
                Register
              </a>
            </li>             
          </ul>   

          {% endif %}      

        </div>
      </div>  
    </nav>

    {% block content %}

    {% endblock %}

    <div class="container">

    <hr>

    <footer>
     
    </footer>

    </div>

  </body>
</html>

travel/forum/templates/forum/detail.html
{% extends 'forumbase.html' %}

{% block title %}
Comment detail
{% endblock %}

{% block content %}
<div style="margin-top: 100px;margin-left: 120px">
	<p>Total Number of Comment(s) : {{ listforum.comments.count }}</p>
	{% if user.is_authenticated %}
	    <a href="{% url 'forum:add_comment' slug=listforum.slug %}">Leave A Comment</a>
   		{% for comment in listforum.comments.all %}
   			<p>{{ comment.created }}</p>
   			<h4>{{ comment.user }}</h4>
   			<p>{{ comment.body }}</p>
            <hr>
        {% endfor %} 
   		
    {% else %}
         {% for comment in listforum.comments.all %}
   			<p>{{ comment.created }}</p>
   			<h4>{{ comment.user }}</h4>
   			<p>{{ comment.body }}</p>
            <hr>
        {% endfor %}
    {% endif %}
</div>
   		        
{% endblock %}

travel/forum/templates/forum/forumindex.html
{% extends 'forumbase.html' %}
{% block title %}
Forums
{% endblock %}

{% block content %}
<div class="jumbotron">
	<div style="margin-top: 30px">
		<h1>These are all The Forums..!!</h1>
	</div>
</div>

<ul>
	{% for forum in all_forum %}
	
	<!-- Method 1 -->
<div >
	<div class="column">
		<li style="color:#A9A9A9;font-size:40px;font-family:serif;list-style: none;background:blue">{{ forum.forum_title }}</li>
		<div style="background:#87CEEB" >
			{% for itemlist in forum.forum_items.all %}
             <li style="list-style: none;font-size:20px;color:black"><a href = "{% url 'forum:detail' slug=itemlist.slug %}">{{ itemlist }}</a></li>
	        {% endfor %}
		</div>		
	</div>
</div>	   
	{% endfor %}
</ul>
{% endblock %}